# Config file for automatic testing at travis-ci.org

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3

script:
  - pip install -U setuptools
  - python setup.py test
